# Generated by Django 3.2.2 on 2021-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20210710_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
