# Generated by Django 3.2.2 on 2021-07-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_alter_orders_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_address',
            field=models.CharField(default='', max_length=120),
        ),
    ]
