# Generated by Django 3.2.2 on 2021-07-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_auto_20210711_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_ac',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_mess',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_roomcleaning',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_vistorentry',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_watercooler',
            field=models.IntegerField(default='0'),
        ),
    ]
